version: 2
jobs:
  build:
    working_directory: /go/src/github.com/ysugimoto/gqb
    docker:
      - image: circleci/golang:1.10
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
    environment:
      GQB_MYSQL_PORT: 3306
    steps:
      - checkout
      - run:
          command: |
            #CirecleCI sets $GOPATH/bin executable autmatically
            curl -L -o $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
            chmod +x $GOPATH/bin/dep
            sudo apt-get update -y && sudo apt-get install -y mysql-client
      - restore_cache:
          keys:
            - v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: dep ensure
      - run:
          name: Run test
          command: make test
      - run:
          name: Run benchmark with real database
          command: make bench

      - save_cache:
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
            - $(go env GOPATH)/bin

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
